### ISSUE TITLE
Why DBML doesn't have some primary features that exists in any ER tool?

### ISSUE THREAD

**Issue by obadakhalili** [holistics/dbml#139]
Why DBML doesn't have some primary features in any ER tool. e.g. Multivalued attributes, derived attributes, week entities, partial keys, etc..
Is it scoped for a particular domain that's not really related to drawing ER diagrams or what?

**Comment by nvquanghuy** [comment]
Hi! Could you elaborate a little bit on those functionalities please? DBML is designed as a logical interface on top of your database **structures**. Are you referring to dbdiagram or DBML?

**Comment by obadakhalili** [comment]
I understand that DBML is an engine that consists of a parser, an importer, and an exporter. And dbdiagram is a web application that uses DBML API. So whenever I want to add a new feature to my diagram in dbdiagram, I look up the DBML docs. But I can't find some primary features that I need for my DB ER-model. e.g. Week entities, multivalued attributes.

I have to admit it's a smart idea to create a platform that transforms your code into an ER-model. it saves you the frustration of having to drag/drop things around and make them look good, but, sadly, the features I'm looking for don't exist in the API.

**Comment by nvquanghuy** [comment]
Thanks for the elaboration @obadakhalili, yes your understanding is correct. I also acknowledge that we don't have such functionalities like weak entities, multivalued attributes etc at the moment.

This is something we need to think harder into, since DBML is designed to be the direct compatible with database schema structure, not ER diagrams. So we need to study more if there's a direct mapping between ER diagrams with SQL DDL representation of it.

Thank you for your input!

**Comment by obadakhalili** [comment]
I see your point @nvquanghuy. DBML is another way of describing the conceptual schema, but instead of manipulating the catalog of a database (similar to what a DDL compiler does), it visualizes your schema.

Thanks for taking the time to elaborate!
