### ISSUE TITLE
 (1:10) Expected " ", "[", "{", comment, or whitespace but "." found.

### ISSUE THREAD

**Issue by RodneyBux** [holistics/dbml#250]
I imported a database generated by SQL Server and I'm getting the error  (1:10) Expected " ", "[", "{", comment, or whitespace but "." found.
[script.zip](https://github.com/holistics/dbml/files/8427149/script.zip)

**Comment by TeaNguyen** [comment]
There're some small barricades with your script. However, we've parsed your file successfully with these steps:
* The file's current encoding is "UTF-16LE", which we haven't supported. So you need to convert the encoding to "UTF-8."
* We don't support the `EXEC` statement at the end of the file, so you need to comment/remove it.
* Make sure you use the `@dbml/cli` version `2.4.0` & use the `sql2dbml` command with `--mssql` option (https://github.com/holistics/dbml/issues/208)

On the other hand, since we don't fully support the ALTER statements, many relationships will be missed in the output.
