### ISSUE TITLE
[bug] incorrect table note parsing by dbml2sql

### ISSUE THREAD

**Issue by dirkdevries96** [holistics/dbml#344]
table notes declared in dbml are not converted correctly to SQL (with flag --postgres). 

This dmbl:
```
Table person {
  note "Stores information about a person"
  id int [pk, increment]
  name varchar
}
```

converts to this SQL:
```
CREATE TABLE "person" (
  "note" "Stores information about a person"
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar
);
```
PostgresSQL interprets the note as a column.

The correct way to declare the table with the comment is:
```
CREATE TABLE "person" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar
);
COMMENT ON TABLE "person" IS 'Stores information about a person';
```

**Comment by huyphung1602** [comment]
Hi @dirkdevries96,

Thank you for using DBML. Because the grammar here is incorrect, the table notes declared in DBML are not converted properly to SQL:
- The note definition must come after all of the column definitions.
- That should be 'note:' instead of 'note'. Missing the 

I hope this one was helping.

**Comment by dirkdevries96** [comment]
Thank you
