### ISSUE TITLE
Indexes / Increment

### ISSUE THREAD

**Issue by edilsonsilvapro** [holistics/dbml#4]
Is there any forecast for implementation of auto increment and indexes?

**Comment by alai04** [comment]
Same question

**Comment by duhyundev** [comment]
me too

**Comment by datashaman** [comment]
for single column indexes, a simple `[index]` would suffice and should be pretty quick to implement.

**Comment by JiawenKor** [comment]
Hi @edilsonsilvapro @alai04 @duhyundev @datashaman, thank you all for looking out for auto increment and indexes!

dbdiagram.io will be launching indexes this week and auto increment will be forecasted near the end of July. The reason for the longer time for auto increment is because we are currently working on a better MySQL and PostgreSQL import experience for our users. We will start on auto increment after that. We hope you understand and we look forward to presenting you a better dbdiagram.io!

**Comment by growth-holistics** [comment]
Hi @edilsonsilvapro @alai04 @duhyundev @datashaman, indexes have been launched! Do try it out and let us know if you have any feedback! Release Notes [here](https://dbdiagram.noting.io/789hqz/support-index-for-tables).

**Comment by JiawenKor** [comment]
Hi @edilsonsilvapro @alai04 @duhyundev @datashaman, indexes have been launched! Do try it out and let us know if you have any feedback! Release Notes [here](https://dbdiagram.noting.io/789hqz/support-index-for-tables).

**Comment by JiawenKor** [comment]
Hi @edilsonsilvapro @alai04 @duhyundev @datashaman, we now support auto-increment! Release Notes [here](https://dbdiagram.noting.io/6vdh5j/support-auto-increment). 

Do check out https://dbdiagram.noting.io/ for latest releases and updates of dbdiagram.io!
