### ISSUE TITLE
unsigned column setting

### ISSUE THREAD

**Issue by datashaman** [holistics/dbml#5]
_unsigned_ should be added to the column settings, it's a very commonly used property of numeric columns and especially primary keys.

Here's a simplified version of the default schema for the _users_ table for a fresh Laravel installation:
```
Table users {
    id bigint [pk, increment, unsigned]
    email varchar [not null, unique]
}
```

**Comment by JiawenKor** [comment]
Hi @datashaman that's a good suggestion for _unsigned_ syntax! I will add it to our backlog and discuss with the team. Thank you!

**Comment by jamiewildehk** [comment]
+1

**Comment by nvquanghuy** [comment]
I just looked into the 3 popular DBs (MySQL, PostgreSQL and MSSQL), and so far only MySQL support `unsigned`, so it's not a popular option.

I'm inclined not to support this attribute yet based on the above observation. I think you can do the following as a workaround when working with mysql:

```
Table users {
    id "bigint unsigned" [pk]
    email varchar [not null, unique]
}
```

**Comment by djpeach** [comment]
Can we document this? If it already is, apologies for now seeing it, but I had to dig to this closed PR to even find that "int unsigned" was supported, especially since 

```
Table User {
  id unsigned [pk]
}
```

did not throw any issues but created faulty sql code for mysql generation. This might just need to be fixed for mysql, but I do prefer being able to use "<int/bignint/smallint/whatever> unsigned", as its way more customized and already supported, just could be documented better.
