### ISSUE TITLE
Support for Views (Virtual Tables)

### ISSUE THREAD

**Issue by julioz** [holistics/dbml#74]
In many databases, especially complex ones, [`view`s](https://www.w3schools.com/sql/sql_view.asp) provide a way to select and/or collate data from multiple tables.

It would be interesting to allow DBML to represent virtual tables, that could be possibly drawn in a different way from regular tables in UI renderers.

**Comment by phuongduyphan** [comment]
Hi,

We have the same idea, but we call it `model` instead of `view`. In the future, we might introduce a new concept "data model" which is generally used in an analytics, BI industry and integrate it into (or make it works with) DBML. You can check more details [here](https://docs.holistics.io/docs/data-modeling).

**Comment by jdiaz-cdw** [comment]
Hi! I can see this is an old thread. I was looking at the DBML documentation, and it seems neither `views` nor `models` are supported. Is there a plan to add support for this? I can definitely see the value of it, when representing complex DB models. Any plans to add this to the DBML language?

**Comment by Nidroide** [comment]
Hi!
First time on dbml (from dbdiagrams.io). It's very nice.
Please add views support as they are used not only to display data but also to define some security advanced patterns (security invoker, definer etc. introduced e.g. in postgresql 15 or to define "instead of insert" triggers).
